<a href="https://colab.research.google.com/github/adrian5520/Machine-learning/blob/main/basics/PCA/03_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

In [2]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
data = df.iloc[:, 1:]
target = df.iloc[:, 0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
target.value_counts()

2    71
1    59
3    48
Name: 0, dtype: int64

In [5]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (133, 13)
X_test shape: (45, 13)


In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]

array([[-0.7408,  0.1998, -0.3485,  0.8054, -0.6278, -1.0134, -0.2767,  2.6177, -0.3597, -1.0017, -0.4916,  0.8736, -1.4062],
       [ 0.0527,  1.402 ,  0.0102,  0.6507,  0.9646, -1.4356, -0.7381, -0.089 , -0.8467,  2.0087, -1.7477, -1.9452, -0.6482],
       [ 0.7019,  2.3369, -0.0297,  0.1868, -0.4893, -0.513 , -1.3431,  1.0106, -1.0555, -0.2378, -0.275 , -0.915 , -0.6482],
       [-0.6326, -0.5303, -1.5044,  0.3414, -0.974 , -0.2002, -0.1947, -0.2582, -0.2553, -0.8938,  0.288 ,  1.2599, -0.2546],
       [-0.4042,  1.3752,  0.1696,  1.1147,  0.1338,  0.7849,  0.4513,  0.6722,  0.5623, -1.0601,  0.9377,  0.6303, -0.9288]])

In [7]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

In [8]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulative'] = results['explained_variance_ratio'].cumsum()
results['component'] = results.index + 1
results

explained_variance_ratio  cumulative  component
0                  0.378008    0.378008          1
1                  0.193737    0.571745          2
2                  0.099310    0.671055          3

In [9]:
fig = go.Figure(data=[go.Bar(x=results['component'], y=results['explained_variance_ratio'], name='explained variance ratio'),
                      go.Scatter(x=results['component'], y=results['cumulative'], name='cumulative explained variance')],
                layout=go.Layout(title=f'PCA - {pca.n_components_} components', width=950, template='plotly_dark'))
fig.show()

In [10]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca1', 'pca2', 'pca3', 'target'])
X_train_pca_df.head()

pca1      pca2      pca3  target
0  2.063494  1.557854  0.892575     2.0
1  2.961502 -2.197753 -0.704119     3.0
2  2.562844 -0.634806 -0.128802     3.0
3 -0.115382  2.116156 -0.667084     2.0
4 -0.105673  1.123883  1.688733     2.0

In [11]:
px.scatter_3d(X_train_pca_df, x='pca1', y='pca2', z='pca3', color='target', template='plotly_dark', width=950)


In [12]:
X_train_pca[:5]

array([[ 2.0635,  1.5579,  0.8926],
       [ 2.9615, -2.1978, -0.7041],
       [ 2.5628, -0.6348, -0.1288],
       [-0.1154,  2.1162, -0.6671],
       [-0.1057,  1.1239,  1.6887]])

In [13]:
X_test_pca[:5]

array([[ 1.0156, -0.0883, -0.0475],
       [-1.0706, -0.0939,  5.1398],
       [ 2.5665,  0.0707, -0.933 ],
       [-0.1823,  2.0342, -2.6727],
       [-2.5499, -1.4388, -0.2   ]])